apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-k8s-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-k8s-controller
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: [ "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-k8s-controller
  namespace: default
subjects:
  - kind: ServiceAccount
    name: example-k8s-controller
    namespace: default
roleRef:
  kind: Role
  name: example-k8s-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-k8s-controller
  labels:
    app: example-k8s-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-k8s-controller
  template:
    metadata:
      labels:
        app: example-k8s-controller
    spec:
      serviceAccount: example-k8s-controller
      containers:
      - name: example-k8s-controller
        image: maddox/example-k8s-controller:1.0.0